[project]
name = "django-project"
version = "0.1.0"
description = "Мой первый Django проект"
dependencies = [
    "crispy-bootstrap5>=2025.6",
    "django>=5.2",
    "django-crispy-forms>=2.4",
]

[tool.uv.pip]
